[project]
name = "order_service"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pika>=1.3.2",
    "patterns",
    "aio-pika",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
patterns = { path = "../../patterns" }
